name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 🚀

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen
      placeholder: I would like to see...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - CLI Tools
        - Web Dashboard
        - Key Generation
        - Client Configuration
        - Server Setup Scripts
        - Testing Tools
        - Documentation
        - New Component
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low (Nice to have)
        - Medium (Would be helpful)
        - High (Important for my use case)
        - Critical (Blocking my use case)
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered
      placeholder: I considered...

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context, mockups, or screenshots about the feature request here
      placeholder: This would be useful because...

  - type: checkboxes
    id: healthcare
    attributes:
      label: Healthcare/HIPAA Considerations
      description: Does this feature impact healthcare or HIPAA compliance?
      options:
        - label: This feature may impact HIPAA compliance requirements
        - label: This feature is for healthcare/dental practice use
        - label: This feature requires additional security considerations
